apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connaisseur
resources:
  - release.yaml
  - namespace.yaml
configMapGenerator:
  - name: connaisseur-values
    files:
      - values.yaml=connaisseur-values.yaml
configurations:
  - kustomizeconfig.yaml
