---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    toolkit.fluxcd.io/tenant: app2
    kustomize.toolkit.fluxcd.io/prune: disabled
    securesystemsengineering.connaisseur/webhook: ignore
  name: app2

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app2
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
    eks.amazonaws.com/role-arn: arn:aws:iam::809870132669:role/Readonly-ECR-app2
  name: app2-sa
  namespace: app2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app2
  name: app2-reconciler
  namespace: app2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:app2:reconciler
- kind: ServiceAccount
  name: app2-sa
  namespace: app2

