apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
################ Release for connaisseur ################
  - ../../../sources/external-sources
  - ../../../for-dev/connaisseur
  - ../../../for-dev/sysdig
