apiVersion: v1
kind: Namespace
metadata:
  name: sysdig
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    environment: "${cluster_env:=dev}"
    region: "${cluster_region}"
    cluster_name: "${cluster_name}"
    account_id: "${account_id}"
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
