apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sysdig
  namespace: sysdig
  annotations:
    meta.helm.sh/release-namespace: "sysdig"
    meta.helm.sh/release-name: sysdig
  labels:
    environment: "${cluster_env:=dev}"
    region: "${cluster_region}"
    cluster_name: "${cluster_name}"
    account_id: "${account_id}"
spec:
  releaseName: sysdig
  chart:
    spec:
      chart: sysdig-deploy
      sourceRef:
        kind: HelmRepository
        name: sysdig
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: sysdig-values
