---
namespacedValidation:
  enabled: true
  mode: validate

validators:
- name: myvalidator
  type: cosign
  trust_roots:
  - name: kms_key
    key: |
      awskms:///arn:aws:kms:us-east-1:809870132669:alias/cosign-key

auth:
  secret_name: ecr-token

policy:
- pattern: "809870132669.dkr.ecr.us-east-1.amazonaws.com/pong-app:*"
  validator: myvalidator
  with:
    key: kms_key

