---
namespacedValidation:
  enabled: true
  mode: validate

validators:
- name: myvalidator
  type: cosign
  trust_roots:
  - name: kms_key
    key: |
      awskms:///arn:aws:kms:us-east-1:809870132669:alias/cosign-key

auth:
  secret_name: ecr-token

policy:
- pattern: "809870132669.dkr.ecr.us-east-1.amazonaws.com/pong-app:*"
  validator: myvalidator
  with:
    key: kms_key

alerting:
  cluster_identifier: demo-eks
  admit_request:
    # Creating a new template called sysdig.json inside ./connaisseur/helm/alert_payload_templates
    templates:
      - template: sysdig
        receiver_url: https://us2.app.sysdig.com/api/v1/eventsDispatch/ingest
        fail_if_alert_sending_fails: true
        custom_headers: []
  reject_request:
    templates:
      - template: sysdig
        receiver_url: https://us2.app.sysdig.com/api/v1/eventsDispatch/ingest
        fail_if_alert_sending_fails: true
        custom_headers: []
