apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: connaisseur
resources:
  - namespace.yaml
  - ecr-token-helper.yaml
  - release.yaml
# configMapGenerator:
#   - name: connaisseur-values
#     files:
#       - values.yaml=connaisseur-values.yaml
# configurations:
#   - kustomizeconfig.yaml
