---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app2
  namespace: app2
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: app2-auth
  url: ssh://git@github.com/S3B4SZ17/pong-app

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app2
  namespace: app2
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: app2-saapp2
  sourceRef:
    kind: GitRepository
    name: app2

