---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    toolkit.fluxcd.io/tenant: app1
    kustomize.toolkit.fluxcd.io/prune: disabled
  name: app1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app1
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
    eks.amazonaws.com/role-arn: arn:aws:iam::809870132669:role/Readonly-ECR
  name: app1-sa
  namespace: app1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: app1
  name: app1-reconciler
  namespace: app1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:app1:reconciler
- kind: ServiceAccount
  name: app1-sa
  namespace: app1

